export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

export const PRODUCTS_DELETE_START = 'PRODUCTS_DELETE_START';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_ERROR = 'PRODUCTS_DELETE_ERROR';

export const PRODUCTS_GETONE_START = 'PRODUCTS_GETONE_START';
export const PRODUCTS_GETONE_SUCCESS = 'PRODUCTS_GETONE_SUCCESS';
export const PRODUCTS_GETONE_ERROR = 'PRODUCTS_GETONE_ERROR';
