export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const USER_GET_ONE_START = 'PRODUCTS_GETONE_START';
export const USER_GET_ONE_SUCCESS = 'PRODUCTS_GETONE_SUCCESS';
export const USER_GET_ONE_ERROR = 'PRODUCTS_GETONE_ERROR';

export const USER_EDIT_INFO_START = 'USER_EDIT_INFO_START';
export const USER_EDIT_INFO_SUCCESS = 'USER_EDIT_INFO_SUCCESS';
export const USER_EDIT_INFO_ERROR = 'USER_EDIT_INFO_ERROR';

export const USER_CHANGE_PASWORD_START = 'USER_EDIT_INFO_START';
export const USER_CHANGE_PASWORD_SUCCESS = 'USER_EDIT_INFO_SUCCESS';
export const USER_CHANGE_PASWORD_ERROR = 'USER_EDIT_INFO_ERROR';

export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

export const PRODUCTS_DELETE_START = 'PRODUCTS_DELETE_START';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_ERROR = 'PRODUCTS_DELETE_ERROR';

export const PRODUCTS_GETONE_START = 'PRODUCTS_GETONE_START';
export const PRODUCTS_GETONE_SUCCESS = 'PRODUCTS_GETONE_SUCCESS';
export const PRODUCTS_GETONE_ERROR = 'PRODUCTS_GETONE_ERROR';

export const PRODUCT_ADD_START = 'PRODUCT_ADD_START';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';

export const PRODUCTS_UPDATE_ONE_START = 'PRODUCTS_UPDATE_ONE_START';
export const PRODUCTS_UPDATE_ONE_SUCCESS = 'PRODUCTS_UPDATE_ONE_SUCCESS';
export const PRODUCTS_UPDATE_ONE_ERROR = 'PRODUCTS_UPDATE_ERROR';
