export const USER_GET_ONE_START = 'PRODUCTS_GETONE_START';
export const USER_GET_ONE_SUCCESS = 'PRODUCTS_GETONE_SUCCESS';
export const USER_GET_ONE_ERROR = 'PRODUCTS_GETONE_ERROR';

export const USER_EDIT_INFO_START = 'USER_EDIT_INFO_START';
export const USER_EDIT_INFO_SUCCESS = 'USER_EDIT_INFO_SUCCESS';
export const USER_EDIT_INFO_ERROR = 'USER_EDIT_INFO_ERROR';

export const USER_CHANGE_PASWORD_START = 'USER_EDIT_INFO_START';
export const USER_CHANGE_PASWORD_SUCCESS = 'USER_EDIT_INFO_SUCCESS';
export const USER_CHANGE_PASWORD_ERROR = 'USER_EDIT_INFO_ERROR';