export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

export const PRODUCTS_DELETE_START = 'PRODUCTS_DELETE_START';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_ERROR = 'PRODUCTS_DELETE_ERROR';

export const PRODUCTS_GETONE_START = 'PRODUCTS_GETONE_START';
export const PRODUCTS_GETONE_SUCCESS = 'PRODUCTS_GETONE_SUCCESS';
export const PRODUCTS_GETONE_ERROR = 'PRODUCTS_GETONE_ERROR';

export const PRODUCT_ADD_START = 'PRODUCT_ADD_START';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';

export const PRODUCTS_UPDATE_ONE_START = 'PRODUCTS_UPDATE_ONE_START';
export const PRODUCTS_UPDATE_ONE_SUCCESS = 'PRODUCTS_UPDATE_ONE_SUCCESS';
export const PRODUCTS_UPDATE_ONE_ERROR = 'PRODUCTS_UPDATE_ERROR';